import {
  Client,
  BillRecord,
  PaymentReceipt,
  SupportTicket,
  MikrotikServerItem,
  PopReseller,
  AutomatedProcessItem,
  SmsTemplateItem
} from './types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: '1',
    code: '0006',
    username: 'haven',
    name: 'Younus Ali',
    password: '••••••••',
    mobile: '01710287818',
    email: 'bbnoffice20@gmail.com',
    nid: '1992491284719283',
    zone: 'Jamtola',
    subzone: 'Bot Tola',
    box: 'Box-04',
    connectionType: 'Optical Fiber',
    clientType: 'Home',
    address: 'Jamtola, Bhurungamari',
    permanentAddress: 'Jamtola, Bhurungamari, Kurigram',
    packageSpeed: '10Mbps/10mb_pkg_500tk',
    packageName: '10Mbps',
    monthlyBill: 500,
    macAddress: '1C:EF:03:E4:EB:C1',
    server: 'BBN-CORE',
    billingStatus: 'Active',
    mikrotikStatus: true,
    joiningDate: '07 Mar 2021',
    expireDate: 27,
    balanceDue: 0,
    lastLogin: '14-Sep-2026 10:05 AM',
    isVip: false,
    allocatedIp: '10.10.2.197'
  },
  {
    id: '2',
    code: '0007',
    username: 'rokon',
    name: 'Rokon',
    password: '••••••••',
    mobile: '01737358063',
    email: 'rokon.bbn@gmail.com',
    nid: '1988491290384721',
    zone: 'Jamtola',
    subzone: 'College Road',
    box: 'Box-01',
    connectionType: 'Optical Fiber',
    clientType: 'Home',
    address: 'Jamtola, Ward 3',
    permanentAddress: 'Jamtola, Bhurungamari',
    packageSpeed: '10Mbps/10mb_pkg_500tk',
    packageName: '10Mbps',
    monthlyBill: 500,
    macAddress: '80:9F:E4:A1:77:08',
    server: 'BBN-CORE',
    billingStatus: 'Active',
    mikrotikStatus: true,
    joiningDate: '03 Feb 2021',
    expireDate: 5,
    balanceDue: 0,
    lastLogin: '14-Sep-2026 08:30 AM',
    isVip: false,
    allocatedIp: '10.10.3.91'
  },
  {
    id: '3',
    code: '0008',
    username: 'kafil',
    name: 'Md. Kofil Mia',
    password: '••••••••',
    mobile: '01724512603',
    email: 'kofil.mia@gmail.com',
    nid: '1995491029384722',
    zone: 'College Para',
    subzone: 'Hospital Para',
    box: 'Box-08',
    connectionType: 'Optical Fiber',
    clientType: 'Shop User',
    address: 'College Para Bazar',
    permanentAddress: 'College Para, Kurigram',
    packageSpeed: '10Mbps/10mb_pkg_500tk',
    packageName: '10Mbps',
    monthlyBill: 500,
    macAddress: 'BC:62:CE:08:48:4F',
    server: 'BBN-CORE',
    billingStatus: 'Active',
    mikrotikStatus: true,
    joiningDate: '03 Jan 2021',
    expireDate: 6,
    balanceDue: 0,
    lastLogin: '13-Sep-2026 11:20 PM',
    isVip: false,
    allocatedIp: '10.10.1.248'
  },
  {
    id: '4',
    code: '0009',
    username: 'mazibar',
    name: 'Md. Mazibar Rahman',
    password: '••••••••',
    mobile: '01735572752',
    email: 'mazibar.bbn@gmail.com',
    nid: '1984491029384001',
    zone: 'College Para',
    subzone: 'Dewaner Khamar',
    box: 'Box-03',
    connectionType: 'Optical Fiber',
    clientType: 'Home',
    address: 'Dewaner Khamar Road',
    permanentAddress: 'Dewaner Khamar, Bhurungamari',
    packageSpeed: '10Mbps/10mb_pkg_500tk',
    packageName: '10Mbps',
    monthlyBill: 500,
    macAddress: '9C:A2:F4:FF:23:8F',
    server: 'BBN-CORE',
    billingStatus: 'Active',
    mikrotikStatus: true,
    joiningDate: '03 Jan 2021',
    expireDate: 9,
    balanceDue: 0,
    lastLogin: '14-Sep-2026 09:12 AM',
    isVip: false,
    allocatedIp: '10.10.2.162'
  },
  {
    id: '5',
    code: '0013',
    username: 'shihab',
    name: 'Md. Mostofa',
    password: '••••••••',
    mobile: '01711802025',
    email: 'mostofa.bbn@gmail.com',
    nid: '1987491029384556',
    zone: 'Jamtola',
    subzone: 'Jamtola Mor',
    box: 'Box-02',
    connectionType: 'Optical Fiber',
    clientType: 'Home',
    address: 'Jamtola Master Para',
    permanentAddress: 'Jamtola Master Para',
    packageSpeed: '50Mbps/50mb_pkg_800tk',
    packageName: '50Mbps',
    monthlyBill: 800,
    macAddress: '0C:80:63:E0:43:2D',
    server: 'BBN-CORE',
    billingStatus: 'Active',
    mikrotikStatus: true,
    joiningDate: '03 Jan 2021',
    expireDate: 11,
    balanceDue: 0,
    lastLogin: '14-Sep-2026 10:45 AM',
    isVip: true,
    allocatedIp: '10.10.11.251'
  },
  {
    id: '6',
    code: '0014',
    username: 'pappu',
    name: 'Kamran Pappu',
    password: '••••••••',
    mobile: '01767556664',
    email: 'pappu.kamran@gmail.com',
    nid: '1996491029384887',
    zone: 'Jamtola',
    subzone: 'Stand Mor',
    box: 'Box-05',
    connectionType: 'Optical Fiber',
    clientType: 'Home',
    address: 'Stand Mor, Bhurungamari',
    permanentAddress: 'Stand Mor, Bhurungamari',
    packageSpeed: '10Mbps/100mb_pkg_1000tk',
    packageName: '10Mbps',
    monthlyBill: 500,
    macAddress: '3C:52:82:11:AB:60',
    server: 'BBN-CORE',
    billingStatus: 'Active',
    mikrotikStatus: true,
    joiningDate: '03 Aug 2021',
    expireDate: 5,
    balanceDue: 0,
    lastLogin: '14-Sep-2026 07:15 AM',
    isVip: false,
    allocatedIp: '10.10.15.248'
  },
  {
    id: '7',
    code: '0015',
    username: 'rofiqulsir',
    name: 'Rofiqul Islam',
    password: '••••••••',
    mobile: '01716151413',
    email: 'rofiqul.islam@gmail.com',
    nid: '1982491029384334',
    zone: 'Jamtola',
    subzone: 'School Road',
    box: 'Box-07',
    connectionType: 'Optical Fiber',
    clientType: 'Home',
    address: 'Jamtola Girls School Road',
    permanentAddress: 'Jamtola Girls School Road',
    packageSpeed: '10Mbps/10mb_pkg_500tk',
    packageName: '10Mbps',
    monthlyBill: 500,
    macAddress: '24:4B:FE:89:12:44',
    server: 'BBN-CORE',
    billingStatus: 'Active',
    mikrotikStatus: true,
    joiningDate: '03 Jan 2021',
    expireDate: 5,
    balanceDue: 0,
    lastLogin: '13-Sep-2026 09:30 PM',
    isVip: false,
    allocatedIp: '10.10.3.74'
  },
  {
    id: '8',
    code: '0017',
    username: 'nirbachon',
    name: 'Nirbachon Office',
    password: '••••••••',
    mobile: '01738039893',
    email: 'nirbachon.bbn@gmail.com',
    nid: '1990491029384210',
    zone: 'College Para',
    subzone: 'Thana Mor',
    box: 'Box-02',
    connectionType: 'Optical Fiber',
    clientType: 'Corporate',
    address: 'Election Commission Office, Upazila',
    permanentAddress: 'Upazila Complex, Bhurungamari',
    packageSpeed: '10Mbps/10mb_pkg_500tk',
    packageName: '10Mbps',
    monthlyBill: 500,
    macAddress: '74:83:C2:55:09:A1',
    server: 'BBN-CORE',
    billingStatus: 'Active',
    mikrotikStatus: true,
    joiningDate: '03 Jan 2021',
    expireDate: 14,
    balanceDue: 0,
    lastLogin: '14-Sep-2026 09:50 AM',
    isVip: true,
    allocatedIp: '10.10.1.238'
  },
  {
    id: '9',
    code: '1040',
    username: 'sofiquejm',
    name: 'Md Sofique',
    password: '••••••••',
    mobile: '01521463004',
    email: 'sofiquejm@gmail.com',
    nid: '1993491029384112',
    zone: 'Jamtola',
    subzone: 'Bot Tola',
    box: 'Box-06',
    connectionType: 'Optical Fiber',
    clientType: 'Home',
    address: 'Bot Tola, Jamtola',
    permanentAddress: 'Bot Tola, Jamtola, Kurigram',
    packageSpeed: '10Mbps/10mb_pkg_500tk',
    packageName: '10Mbps',
    monthlyBill: 500,
    macAddress: '0C:80:63:E0:43:2D',
    server: 'BBN-CORE',
    billingStatus: 'Active',
    mikrotikStatus: true,
    joiningDate: '01 Feb 2022',
    expireDate: 29,
    balanceDue: 500,
    lastLogin: '14-Sep-2026 10:30 AM',
    isVip: false,
    allocatedIp: '10.10.4.11'
  },
  {
    id: '10',
    code: '1039',
    username: 'faizatnt',
    name: 'Faiza Tasmin Fimu',
    password: '••••••••',
    mobile: '01842826877',
    email: 'faiza.fimu@gmail.com',
    nid: '1998491029384009',
    zone: 'Stand',
    subzone: 'Stand Mor',
    box: 'Box-09',
    connectionType: 'Optical Fiber',
    clientType: 'Home',
    address: 'Stand Mor, Bhurungamari',
    permanentAddress: 'Stand Mor, Bhurungamari',
    packageSpeed: '10Mbps/10mb_pkg_500tk',
    packageName: '10Mbps',
    monthlyBill: 500,
    macAddress: '80:9F:E4:A1:77:08',
    server: 'BBN-CORE',
    billingStatus: 'Active',
    mikrotikStatus: true,
    joiningDate: '15 Mar 2022',
    expireDate: 29,
    balanceDue: 500,
    lastLogin: '14-Sep-2026 08:45 AM',
    isVip: false,
    allocatedIp: '10.10.5.22'
  },
  {
    id: '11',
    code: '1038',
    username: 'lgedsir',
    name: 'LGED Sir',
    password: '••••••••',
    mobile: '01740134626',
    email: 'lged.kurigram@gmail.com',
    nid: '1980491029384777',
    zone: 'Jamtola',
    subzone: 'Hospital Para',
    box: 'Box-01',
    connectionType: 'Optical Fiber',
    clientType: 'Home',
    address: 'Officers Quarter, Jamtola',
    permanentAddress: 'Officers Quarter, Bhurungamari',
    packageSpeed: '20Mbps/20mb_pkg_600tk',
    packageName: '20Mbps',
    monthlyBill: 600,
    macAddress: 'BC:62:CE:08:48:4F',
    server: 'BBN-CORE',
    billingStatus: 'Active',
    mikrotikStatus: true,
    joiningDate: '10 Apr 2022',
    expireDate: 29,
    balanceDue: 600,
    lastLogin: '14-Sep-2026 10:18 AM',
    isVip: true,
    allocatedIp: '10.10.6.33'
  },
  {
    id: '12',
    code: '1037',
    username: 'mehedicp',
    name: 'Md Mehedi Hasan',
    password: '••••••••',
    mobile: '01777538594',
    email: 'mehedi.hasan@gmail.com',
    nid: '1999491029384551',
    zone: 'College Para',
    subzone: 'College Road',
    box: 'Box-04',
    connectionType: 'Optical Fiber',
    clientType: 'Home',
    address: 'College Para, Bhurungamari',
    permanentAddress: 'College Para, Bhurungamari',
    packageSpeed: '10Mbps/10mb_pkg_500tk',
    packageName: '10Mbps',
    monthlyBill: 500,
    macAddress: '9C:A2:F4:FF:23:8F',
    server: 'BBN-CORE',
    billingStatus: 'Active',
    mikrotikStatus: true,
    joiningDate: '01 May 2022',
    expireDate: 29,
    balanceDue: 0,
    lastLogin: '14-Sep-2026 09:00 AM',
    isVip: false,
    allocatedIp: '10.10.7.44'
  }
];

export const INITIAL_BILLING_LIST: BillRecord[] = [
  {
    id: 'b1',
    clientCode: '0006',
    username: 'haven',
    clientName: 'Younus Ali',
    mobile: '01710287818',
    zone: 'Jamtola',
    clientType: 'Home',
    connectionType: 'Optical Fiber',
    address: 'Jamtola',
    package: '10Mbps',
    speed: '10mb_pkg_500tk',
    expireDay: 27,
    monthlyBill: 500.0,
    receivedAmount: 500.0,
    vatAmount: 25.0,
    balanceDue: 0.0,
    advanceAmount: 0.0,
    paymentDate: 'Sep-05-2026',
    server: 'BBN-CORE',
    mikrotikStatus: true,
    billingStatus: 'Paid'
  },
  {
    id: 'b2',
    clientCode: '0007',
    username: 'rokon',
    clientName: 'Rokon',
    mobile: '01737358063',
    zone: 'Jamtola',
    clientType: 'Home',
    connectionType: 'Optical Fiber',
    address: 'Jamtola',
    package: '10Mbps',
    speed: '10mb_pkg_500tk',
    expireDay: 5,
    monthlyBill: 500.0,
    receivedAmount: 500.0,
    vatAmount: 25.0,
    balanceDue: 0.0,
    advanceAmount: 0.0,
    paymentDate: 'Sep-05-2026',
    server: 'BBN-CORE',
    mikrotikStatus: true,
    billingStatus: 'Paid'
  },
  {
    id: 'b3',
    clientCode: '0008',
    username: 'kafil',
    clientName: 'Md. Kofil Mia',
    mobile: '01724512603',
    zone: 'College Para',
    clientType: 'Shop User',
    connectionType: 'Optical Fiber',
    address: 'College Para',
    package: '10Mbps',
    speed: '10mb_pkg_500tk',
    expireDay: 6,
    monthlyBill: 500.0,
    receivedAmount: 500.0,
    vatAmount: 25.0,
    balanceDue: 0.0,
    advanceAmount: 0.0,
    paymentDate: 'Sep-05-2026',
    server: 'BBN-CORE',
    mikrotikStatus: true,
    billingStatus: 'Paid'
  },
  {
    id: 'b4',
    clientCode: '0009',
    username: 'mazibar',
    clientName: 'Md. Mazibar Rahman',
    mobile: '01735572752',
    zone: 'College Para',
    clientType: 'Home',
    connectionType: 'Optical Fiber',
    address: 'College Para',
    package: '10Mbps',
    speed: '10mb_pkg_500tk',
    expireDay: 9,
    monthlyBill: 500.0,
    receivedAmount: 500.0,
    vatAmount: 25.0,
    balanceDue: 0.0,
    advanceAmount: 0.0,
    paymentDate: 'Sep-08-2026',
    server: 'BBN-CORE',
    mikrotikStatus: true,
    billingStatus: 'Paid'
  },
  {
    id: 'b5',
    clientCode: '0013',
    username: 'shihab',
    clientName: 'Md. Mostofa',
    mobile: '01711802025',
    zone: 'Jamtola',
    clientType: 'Home',
    connectionType: 'Optical Fiber',
    address: 'Jamtola',
    package: '50Mbps',
    speed: '50mb_pkg_800tk',
    expireDay: 11,
    monthlyBill: 800.0,
    receivedAmount: 800.0,
    vatAmount: 40.0,
    balanceDue: 0.0,
    advanceAmount: 0.0,
    paymentDate: 'Sep-11-2026',
    server: 'BBN-CORE',
    mikrotikStatus: true,
    billingStatus: 'Paid'
  },
  {
    id: 'b6',
    clientCode: '0014',
    username: 'pappu',
    clientName: 'Kamran Pappu',
    mobile: '01767556664',
    zone: 'Jamtola',
    clientType: 'Home',
    connectionType: 'Optical Fiber',
    address: 'Jamtola',
    package: '10Mbps',
    speed: '100mb_pkg_1000tk',
    expireDay: 5,
    monthlyBill: 500.0,
    receivedAmount: 500.0,
    vatAmount: 25.0,
    balanceDue: 0.0,
    advanceAmount: 0.0,
    paymentDate: 'Sep-05-2026',
    server: 'BBN-CORE',
    mikrotikStatus: true,
    billingStatus: 'Paid'
  },
  {
    id: 'b7',
    clientCode: '0015',
    username: 'rofiqulsir',
    clientName: 'Rofiqul Islam',
    mobile: '01716151413',
    zone: 'Jamtola',
    clientType: 'Home',
    connectionType: 'Optical Fiber',
    address: 'Jamtola',
    package: '10Mbps',
    speed: '10mb_pkg_500tk',
    expireDay: 5,
    monthlyBill: 500.0,
    receivedAmount: 500.0,
    vatAmount: 25.0,
    balanceDue: 0.0,
    advanceAmount: 0.0,
    paymentDate: 'Sep-02-2026',
    server: 'BBN-CORE',
    mikrotikStatus: true,
    billingStatus: 'Paid'
  },
  {
    id: 'b8',
    clientCode: '0017',
    username: 'nirbachon',
    clientName: 'Nirbachon Office',
    mobile: '01738039893',
    zone: 'College Para',
    clientType: 'Corporate',
    connectionType: 'Optical Fiber',
    address: 'College Para',
    package: '10Mbps',
    speed: '10mb_pkg_500tk',
    expireDay: 14,
    monthlyBill: 500.0,
    receivedAmount: 500.0,
    vatAmount: 25.0,
    balanceDue: 0.0,
    advanceAmount: 0.0,
    paymentDate: 'Sep-14-2026',
    server: 'BBN-CORE',
    mikrotikStatus: true,
    billingStatus: 'Paid'
  },
  {
    id: 'b9',
    clientCode: '1040',
    username: 'sofiquejm',
    clientName: 'Md Sofique',
    mobile: '01521463004',
    zone: 'Jamtola',
    clientType: 'Home',
    connectionType: 'Optical Fiber',
    address: 'Jamtola',
    package: '10Mbps',
    speed: '10mb_pkg_500tk',
    expireDay: 29,
    monthlyBill: 500.0,
    receivedAmount: 0.0,
    vatAmount: 25.0,
    balanceDue: 500.0,
    advanceAmount: 0.0,
    server: 'BBN-CORE',
    mikrotikStatus: true,
    billingStatus: 'Unpaid'
  },
  {
    id: 'b10',
    clientCode: '1039',
    username: 'faizatnt',
    clientName: 'Faiza Tasmin Fimu',
    mobile: '01842826877',
    zone: 'Stand',
    clientType: 'Home',
    connectionType: 'Optical Fiber',
    address: 'Stand',
    package: '10Mbps',
    speed: '10mb_pkg_500tk',
    expireDay: 29,
    monthlyBill: 500.0,
    receivedAmount: 0.0,
    vatAmount: 25.0,
    balanceDue: 500.0,
    advanceAmount: 0.0,
    server: 'BBN-CORE',
    mikrotikStatus: true,
    billingStatus: 'Unpaid'
  },
  {
    id: 'b11',
    clientCode: '1038',
    username: 'lgedsir',
    clientName: 'LGED Sir',
    mobile: '01740134626',
    zone: 'Jamtola',
    clientType: 'Home',
    connectionType: 'Optical Fiber',
    address: 'Jamtola',
    package: '20Mbps',
    speed: '20mb_pkg_600tk',
    expireDay: 29,
    monthlyBill: 600.0,
    receivedAmount: 0.0,
    vatAmount: 30.0,
    balanceDue: 600.0,
    advanceAmount: 0.0,
    server: 'BBN-CORE',
    mikrotikStatus: true,
    billingStatus: 'Unpaid'
  },
  {
    id: 'b12',
    clientCode: '0001',
    username: 'amberit',
    clientName: 'Amber IT Point',
    mobile: '01734296501',
    zone: 'Saddam Mor',
    clientType: 'Corporate',
    connectionType: 'Optical Fiber',
    address: 'Main Road',
    package: '100Mbps',
    speed: '100mb_pkg_2000tk',
    expireDay: 29,
    monthlyBill: 2000.0,
    receivedAmount: 0.0,
    vatAmount: 100.0,
    balanceDue: 2000.0,
    advanceAmount: 0.0,
    server: 'BBN-CORE',
    mikrotikStatus: true,
    billingStatus: 'Unpaid'
  }
];

export const INITIAL_RECEIPTS_YOUNUS: PaymentReceipt[] = [
  {
    id: 'rc-1',
    clientCode: '0006',
    receivedDate: '27 Aug 2026',
    receivedBy: 'bKash',
    paymentMethod: 'bKash',
    paymentInfo: 'Payment by bKash (Txn: 9AJ2394KA)',
    createdBy: '0006',
    remarks: 'Customer self portal payment',
    discount: 0,
    receivedBill: 500,
    totalBill: 500,
    vat: 25,
    balanceDue: 0,
    receiptNo: 'REC-2026-08006',
    month: 'August 2026'
  },
  {
    id: 'rc-2',
    clientCode: '0006',
    receivedDate: '27 Jul 2026',
    receivedBy: 'bKash',
    paymentMethod: 'bKash',
    paymentInfo: 'Payment by bKash (Txn: 8LK3849LK)',
    createdBy: '0006',
    remarks: 'Customer self portal payment',
    discount: 0,
    receivedBill: 500,
    totalBill: 500,
    vat: 25,
    balanceDue: 0,
    receiptNo: 'REC-2026-07006',
    month: 'July 2026'
  },
  {
    id: 'rc-3',
    clientCode: '0006',
    receivedDate: '27 Jun 2026',
    receivedBy: 'bKash',
    paymentMethod: 'bKash',
    paymentInfo: 'Payment by bKash (Txn: 7PP9821MN)',
    createdBy: '0006',
    remarks: 'Customer self portal payment',
    discount: 0,
    receivedBill: 500,
    totalBill: 500,
    vat: 25,
    balanceDue: 0,
    receiptNo: 'REC-2026-06006',
    month: 'June 2026'
  },
  {
    id: 'rc-4',
    clientCode: '0006',
    receivedDate: '27 May 2026',
    receivedBy: 'bKash',
    paymentMethod: 'bKash',
    paymentInfo: 'Payment by bKash (Txn: 6NM1928ZA)',
    createdBy: '0006',
    remarks: 'Customer self portal payment',
    discount: 0,
    receivedBill: 500,
    totalBill: 500,
    vat: 25,
    balanceDue: 0,
    receiptNo: 'REC-2026-05006',
    month: 'May 2026'
  },
  {
    id: 'rc-5',
    clientCode: '0006',
    receivedDate: '05 Mar 2026',
    receivedBy: 'bKash',
    paymentMethod: 'bKash',
    paymentInfo: 'Payment by bKash (Txn: 5TR4910PL)',
    createdBy: '0006',
    remarks: 'Customer self portal payment',
    discount: 0,
    receivedBill: 500,
    totalBill: 500,
    vat: 25,
    balanceDue: 0,
    receiptNo: 'REC-2026-03006',
    month: 'March 2026'
  },
  {
    id: 'rc-6',
    clientCode: '0006',
    receivedDate: '10 Jan 2026',
    receivedBy: 'Md Assaduzzman Asad',
    paymentMethod: 'Cash',
    paymentInfo: 'Payment by Cash',
    createdBy: 'bbnasad',
    remarks: 'Counter payment collected',
    discount: 0,
    receivedBill: 500,
    totalBill: 500,
    vat: 25,
    balanceDue: 0,
    receiptNo: 'REC-2026-01006',
    month: 'January 2026'
  }
];

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    ticketNo: '635',
    clientCode: '0920',
    username: 'jonydk',
    customerName: 'Md Jony',
    mobile: '01762848282',
    complainNo: '01762848282',
    zone: 'Stand',
    subzone: 'Bot Tola',
    box: 'Box-01',
    problem: 'Forget Password',
    priority: 'High',
    complainTime: '05 Sep 2026 09:22 PM',
    createdBy: 'bbnasad',
    status: 'Processing',
    assignTo: 'Sobuj Biplob (09-05-26)',
    duration: '8d:14h:18m:55s',
    note: 'Client needs PPPoE credentials reset on Mikrotik server.'
  },
  {
    ticketNo: '636',
    clientCode: '0374',
    username: 'jafordk',
    customerName: 'MD Abu Jafar',
    mobile: '01713746916',
    complainNo: '01713746916',
    zone: 'Stand',
    subzone: 'Dewaner Khamar',
    box: 'Box-04',
    problem: 'No Internet',
    priority: 'High',
    complainTime: '05 Sep 2026 09:23 PM',
    createdBy: 'bbnasad',
    status: 'Processing',
    assignTo: 'Rasel Hossain (09-05-26)',
    duration: '8d:14h:18m:17s',
    note: 'ONU red LOS light blinking. Field team assigned for patch cord check.'
  },
  {
    ticketNo: '645',
    clientCode: '0540',
    username: 'miraztr',
    customerName: 'Md Miraz',
    mobile: '01791840350',
    complainNo: '01791840350',
    zone: 'Stand',
    subzone: 'Thana',
    box: 'Box-03',
    problem: 'Speed Issue',
    priority: 'High',
    complainTime: '08 Sep 2026 05:54 PM',
    createdBy: 'bbnasad',
    status: 'Processing',
    assignTo: 'Sobuj Biplob (09-08-26)',
    duration: '5d:17h:47m:27s',
    note: 'High latency during peak hours. Mikrotik queue checking.'
  },
  {
    ticketNo: '647',
    clientCode: '0838',
    username: 'rashedkg',
    customerName: 'Md Rashed',
    mobile: '01835831089',
    complainNo: '01835831089',
    zone: 'Stand',
    subzone: 'KG ROAD',
    box: 'Box-07',
    problem: 'Pon Loss',
    priority: 'High',
    complainTime: '10 Sep 2026 02:47 PM',
    createdBy: 'bbnasad',
    status: 'Processing',
    assignTo: 'Rasel Hossain (09-10-26)',
    duration: '3d:20h:53m:39s',
    note: 'Splice tray inspection needed at KG Road pole 14.'
  },
  {
    ticketNo: '648',
    clientCode: '1017',
    username: 'tanvircp2',
    customerName: 'Md Tanvir',
    mobile: '01717180036',
    complainNo: '01717180036',
    zone: 'College Para',
    subzone: 'College Road',
    box: 'Box-02',
    problem: 'No Internet',
    priority: 'High',
    complainTime: '10 Sep 2026 02:48 PM',
    createdBy: 'bbnasad',
    status: 'Processing',
    assignTo: 'Sobuj Biplob (09-10-26)',
    duration: '3d:20h:53m:3s',
    note: 'Dropped fiber near College main gate due to electric pole maintenance.'
  }
];

export const INITIAL_MIKROTIK_SERVERS: MikrotikServerItem[] = [
  {
    id: 'srv-1',
    serial: 1,
    name: 'BBN-CORE',
    ip: '157.10.238.100',
    username: 'apionline',
    port: 1122,
    version: 'v3 (RouterOS 7.14)',
    timeout: '10 sec.',
    status: true,
    activeClients: 631,
    latencyMs: 4,
    cpuUsage: 14,
    uptime: '142 days, 18:42:10'
  },
  {
    id: 'srv-2',
    serial: 2,
    name: 'MikroTik Backup',
    ip: '157.10.238.38',
    username: 'apionline',
    port: 1122,
    version: 'v3 (RouterOS 7.12)',
    timeout: '10 sec.',
    status: false,
    activeClients: 0,
    latencyMs: 0,
    cpuUsage: 2,
    uptime: 'Standby'
  }
];

export const INITIAL_POPS: PopReseller[] = [
  {
    code: '0002',
    name: 'BBN- Joymonirhat Branch',
    type: 'Prepaid',
    contactPerson: 'S.M Monzurul Kabir Zinnia',
    serverName: 'BBN-CORE',
    mobile: '01744226679',
    companyName: 'BBN- Joymonirhat Branch',
    level: 'Level 1',
    tariffName: 'Zinnia',
    clientsRunning: 115,
    clientsEnabled: 38,
    clientsDisabled: 77,
    clientsLeft: 24,
    remainingFund: 441.47,
    clientEnabled: true,
    fundStart: true,
    isLocked: false
  }
];

export const INITIAL_AUTOMATED_PROCESSES: AutomatedProcessItem[] = [
  {
    id: 'proc-1',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Fund Credit & Disable of Postpaid POPs',
    executeAt: '00:05',
    interval: 'Daily',
    executionDay: 'Today',
    status: 'Active',
    lastRun: '14-Sep-2026 00:05:01',
    nextRun: '15-Sep-2026 00:05:00',
    description: 'Calculates remaining balance for postpaid POP partners, applies fund credits from bank/bKash receipts, and disables delinquent POP branches with negative balance beyond credit limit.',
    targetSubsystem: 'POP Ledger & MikroTik CCR Core',
    cronPattern: '05 00 * * *',
    recordsAffected: 4,
    lastRunDuration: '1.24s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-2',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Check Negative Balance of MAC Resellers',
    executeAt: '07:00',
    interval: 'Daily',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 07:00:15',
    nextRun: '15-Sep-2026 07:00:00',
    description: 'Scans all MAC-based sub-resellers for overdue balances, validates prepaid credit thresholds, and sends threshold alerts to accounting.',
    targetSubsystem: 'MAC Reseller Accounting Engine',
    cronPattern: '00 07 * * *',
    recordsAffected: 2,
    lastRunDuration: '0.85s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-3',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Disable Unpaid Customers',
    executeAt: '11:00',
    interval: 'Daily',
    executionDay: 'Today',
    status: 'Active',
    lastRun: '14-Sep-2026 11:00:00',
    nextRun: '15-Sep-2026 11:00:00',
    description: 'Queries subscribers with passed expiration dates without recorded receipt, disables their PPPoE secret on active MikroTik routers, and moves session to walled-garden pool.',
    targetSubsystem: 'MikroTik RouterOS 7.x (PPPoE Secrets)',
    cronPattern: '00 11 * * *',
    recordsAffected: 18,
    lastRunDuration: '3.42s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-4',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Sync All Customer By Servers',
    executeAt: 'Default',
    interval: 'Hourly',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 10:00:00',
    nextRun: '14-Sep-2026 11:00:00',
    description: 'Bidirectional state synchronization between central billing database and all MikroTik routers (BBN-CORE, Standby NAS) to audit orphaned secrets.',
    targetSubsystem: 'MikroTik API (Port 8728)',
    cronPattern: '00 * * * *',
    recordsAffected: 631,
    lastRunDuration: '5.18s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-5',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Generate Monthly Bill of Customers',
    executeAt: '06:00',
    interval: 'Daily',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '01-Sep-2026 06:00:00',
    nextRun: '01-Oct-2026 06:00:00',
    description: 'Generates automated monthly recurring billing ledger entries, applies VAT (5%), and queues client payment notifications for retail subscribers.',
    targetSubsystem: 'Billing Ledger & Invoicing Engine',
    cronPattern: '00 06 01 * *',
    recordsAffected: 580,
    lastRunDuration: '4.72s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-6',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Send SMS To Unpaid Customers Before Expiry Date',
    executeAt: '08:30',
    interval: 'Daily',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 08:30:20',
    nextRun: '15-Sep-2026 08:30:00',
    description: 'Sends SMS billing reminders with bKash/Nagad direct payment links to customers whose subscriptions expire within 48 hours.',
    targetSubsystem: 'Onnorokom / Greenweb SMS Gateway',
    cronPattern: '30 08 * * *',
    recordsAffected: 36,
    lastRunDuration: '2.15s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-7',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Package Scheduler of Customers',
    executeAt: '23:40',
    interval: 'Daily',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '13-Sep-2026 23:40:00',
    nextRun: '14-Sep-2026 23:40:00',
    description: 'Executes queued bandwidth upgrade and downgrade requests effective on the next calendar day in MikroTik queue trees.',
    targetSubsystem: 'MikroTik Simple Queues & PCQ',
    cronPattern: '40 23 * * *',
    recordsAffected: 5,
    lastRunDuration: '0.92s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-8',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Status Scheduler of Customers',
    executeAt: '23:30',
    interval: 'Daily',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '13-Sep-2026 23:30:00',
    nextRun: '14-Sep-2026 23:30:00',
    description: 'Processes planned subscriber state transitions (vacation freeze, scheduled reactivation, service reconnection).',
    targetSubsystem: 'CRM Lifecycle Controller',
    cronPattern: '30 23 * * *',
    recordsAffected: 3,
    lastRunDuration: '0.64s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-9',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Generate Recurring Bandwidth Sale Invoice',
    executeAt: '03:00',
    interval: 'Daily',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '01-Sep-2026 03:00:00',
    nextRun: '01-Oct-2026 03:00:00',
    description: 'Generates wholesale bandwidth sale invoices for corporate leased line clients and POP transit handoffs.',
    targetSubsystem: 'Wholesale Billing Accounting Module',
    cronPattern: '00 03 01 * *',
    recordsAffected: 8,
    lastRunDuration: '1.05s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-10',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Generate Monthly Bill of MAC Resellers',
    executeAt: '05:15',
    interval: 'Daily',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '01-Sep-2026 05:15:00',
    nextRun: '01-Oct-2026 05:15:00',
    description: 'Computes monthly revenue-share statements and wholesale tariff bills for all registered MAC sub-operators.',
    targetSubsystem: 'Reseller Billing Engine',
    cronPattern: '15 05 01 * *',
    recordsAffected: 12,
    lastRunDuration: '1.88s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-11',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Send SMS To Unpaid MAC Client Before Expiry Date',
    executeAt: '08:45',
    interval: 'Daily',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 08:45:00',
    nextRun: '15-Sep-2026 08:45:00',
    description: 'Notifies subscribers under MAC resellers whose account validity is nearing expiration.',
    targetSubsystem: 'Telecom SMS Aggregator',
    cronPattern: '45 08 * * *',
    recordsAffected: 24,
    lastRunDuration: '1.45s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-12',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Delete Extra MAC Reseller Mikrotik Users',
    executeAt: '05:30',
    interval: 'Daily',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 05:30:00',
    nextRun: '15-Sep-2026 05:30:00',
    description: 'Cleans up unauthorized or unbilled PPPoE users created in MikroTik that exceed quota limits.',
    targetSubsystem: 'MikroTik Security Daemon',
    cronPattern: '30 05 * * *',
    recordsAffected: 0,
    lastRunDuration: '2.10s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-13',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Execute Manual Processes',
    executeAt: 'Default',
    interval: 'Minutely',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 10:24:00',
    nextRun: '14-Sep-2026 10:25:00',
    description: 'Asynchronous worker polling every 60 seconds to process manual admin triggers and queue items.',
    targetSubsystem: 'Background Redis / Job Worker',
    cronPattern: '* * * * *',
    recordsAffected: 1,
    lastRunDuration: '0.12s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-14',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Sync Expire Date With CRM',
    executeAt: '01:40',
    interval: 'Daily',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 01:40:00',
    nextRun: '15-Sep-2026 01:40:00',
    description: 'Reconciles payment collection dates with subscriber validity dates to eliminate billing discrepancies.',
    targetSubsystem: 'Core Database Reconciler',
    cronPattern: '40 01 * * *',
    recordsAffected: 14,
    lastRunDuration: '1.60s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-15',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Validate Payments of Customers',
    executeAt: 'Default',
    interval: 'Hourly',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 10:00:00',
    nextRun: '14-Sep-2026 11:00:00',
    description: 'Verifies pending online transactions from bKash, Nagad, and Rocket webhooks against merchant settlement logs.',
    targetSubsystem: 'Payment Gateway Webhook IPN Listener',
    cronPattern: '00 * * * *',
    recordsAffected: 7,
    lastRunDuration: '1.10s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-16',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Disable MAC Reseller Users For Low Balance',
    executeAt: 'Default',
    interval: 'Hourly',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 10:00:00',
    nextRun: '14-Sep-2026 11:00:00',
    description: 'Suspends PPPoE users of resellers whose prepaid balance or credit ceiling has been depleted.',
    targetSubsystem: 'MikroTik RouterOS 7.x',
    cronPattern: '00 * * * *',
    recordsAffected: 0,
    lastRunDuration: '1.45s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-17',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Process for Attendance Logs',
    executeAt: 'Default',
    interval: 'Hourly',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 10:00:00',
    nextRun: '14-Sep-2026 11:00:00',
    description: 'Pulls biometric attendance and punch logs from office ZKTeco biometric devices to HR payroll system.',
    targetSubsystem: 'ZKTeco BioTime API',
    cronPattern: '00 * * * *',
    recordsAffected: 11,
    lastRunDuration: '0.78s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-18',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Disabled Unpaid Customers Status Change To InActive',
    executeAt: '23:20',
    interval: 'Daily',
    executionDay: 'Today',
    status: 'Active',
    lastRun: '13-Sep-2026 23:20:00',
    nextRun: '14-Sep-2026 23:20:00',
    description: 'Converts customer status from Disabled to Inactive after 30 consecutive days of delinquency.',
    targetSubsystem: 'CRM Lifecycle State Machine',
    cronPattern: '20 23 * * *',
    recordsAffected: 2,
    lastRunDuration: '0.45s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-19',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Prepaid POP Clients Automatic Renewal & Disable',
    executeAt: '01:05',
    interval: 'Daily',
    executionDay: 'Today',
    status: 'Active',
    lastRun: '14-Sep-2026 01:05:00',
    nextRun: '15-Sep-2026 01:05:00',
    description: 'Renews prepaid POP subscriber packages against available POP fund balance; disables accounts if insufficient balance.',
    targetSubsystem: 'POP Automated Wallet Manager',
    cronPattern: '05 01 * * *',
    recordsAffected: 9,
    lastRunDuration: '1.92s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-20',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Prepaid MACReseller Clients Validity Checker',
    executeAt: '00:30',
    interval: 'Daily',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 00:30:00',
    nextRun: '15-Sep-2026 00:30:00',
    description: 'Audits expiration dates for all prepaid sub-reseller users and flags lines requiring voucher recharge.',
    targetSubsystem: 'Reseller Sub-Subscriber Validator',
    cronPattern: '30 00 * * *',
    recordsAffected: 15,
    lastRunDuration: '1.30s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-21',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Sync All MACReseller Clients By Servers',
    executeAt: 'Default',
    interval: 'Hourly',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 10:00:00',
    nextRun: '14-Sep-2026 11:00:00',
    description: 'Reconciles MAC reseller client profiles across all physical MikroTik NAS routers.',
    targetSubsystem: 'MikroTik CCR PPPoE Server',
    cronPattern: '00 * * * *',
    recordsAffected: 84,
    lastRunDuration: '2.40s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-22',
    branch: 'Main Branch',
    category: 'System',
    processName: 'CRM Eligibility Checker',
    executeAt: '04:15',
    interval: 'Daily',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 04:15:00',
    nextRun: '15-Sep-2026 04:15:00',
    description: 'Evaluates subscribers for loyalty bonuses, BTRC compliance documentation, and speed promotion eligibility.',
    targetSubsystem: 'CRM Analytics Engine',
    cronPattern: '15 04 * * *',
    recordsAffected: 12,
    lastRunDuration: '0.95s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-23',
    branch: 'Main Branch',
    category: 'System',
    processName: 'New Year Billing Period Create Or Activation',
    executeAt: '00:00',
    interval: 'Yearly',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '01-Jan-2026 00:00:00',
    nextRun: '01-Jan-2027 00:00:00',
    description: 'Creates annual financial fiscal periods, resets sequential voucher counters, and prepares accounting calendars.',
    targetSubsystem: 'Accounting Fiscal Period Manager',
    cronPattern: '00 00 01 01 *',
    recordsAffected: 1,
    lastRunDuration: '3.10s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-24',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Disable Customers In Mikrotik',
    executeAt: '00:00',
    interval: 'Custom',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '10-Sep-2026 23:59:00',
    nextRun: 'Manual Trigger',
    description: 'Instant batch disable command to disconnect all delinquent clients on chosen MikroTik server.',
    targetSubsystem: 'MikroTik API Command Queue',
    cronPattern: 'Manual / On-Demand',
    recordsAffected: 0,
    lastRunDuration: '1.50s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-25',
    branch: 'Main Branch',
    category: 'System',
    processName: 'Send Queue SMS To Unpaid Customers',
    executeAt: '00:00',
    interval: 'Custom',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '12-Sep-2026 14:00:00',
    nextRun: 'Manual Trigger',
    description: 'Flushes and transmits all queued outbound SMS notifications through SMS aggregator API.',
    targetSubsystem: 'SMS Outbox Dispatcher',
    cronPattern: 'Manual / On-Demand',
    recordsAffected: 45,
    lastRunDuration: '2.80s',
    lastRunStatus: 'Success'
  },
  // Admin Customer Tab Processes
  {
    id: 'proc-ac-1',
    branch: 'Main Branch',
    category: 'Admin Customer',
    processName: 'Retail Customer Monthly Invoicing',
    executeAt: '06:00',
    interval: 'Monthly',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '01-Sep-2026 06:00:00',
    nextRun: '01-Oct-2026 06:00:00',
    description: 'Generates retail customer bills for all active Home & Corporate accounts for the billing cycle.',
    targetSubsystem: 'Invoicing Engine',
    cronPattern: '00 06 01 * *',
    recordsAffected: 580,
    lastRunDuration: '4.2s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-ac-2',
    branch: 'Main Branch',
    category: 'Admin Customer',
    processName: 'Auto-Disable Past Expiry Day Unpaid Accounts',
    executeAt: '11:00',
    interval: 'Daily',
    executionDay: 'Today',
    status: 'Active',
    lastRun: '14-Sep-2026 11:00:00',
    nextRun: '15-Sep-2026 11:00:00',
    description: 'Disables PPPoE credentials of retail clients who reached due date without completing payment.',
    targetSubsystem: 'MikroTik BBN-CORE',
    cronPattern: '00 11 * * *',
    recordsAffected: 18,
    lastRunDuration: '3.1s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-ac-3',
    branch: 'Main Branch',
    category: 'Admin Customer',
    processName: 'Customer Expiry Warning SMS Notification',
    executeAt: '08:30',
    interval: 'Daily',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 08:30:00',
    nextRun: '15-Sep-2026 08:30:00',
    description: 'Sends SMS alerts 2 days prior to billing expiration with online payment URL.',
    targetSubsystem: 'SMS Gateway',
    cronPattern: '30 08 * * *',
    recordsAffected: 36,
    lastRunDuration: '1.9s',
    lastRunStatus: 'Success'
  },
  // POP Tab Processes
  {
    id: 'proc-pop-1',
    branch: 'Main Branch',
    category: 'POP',
    processName: 'Fund Credit & Disable of Postpaid POPs',
    executeAt: '00:05',
    interval: 'Daily',
    executionDay: 'Today',
    status: 'Active',
    lastRun: '14-Sep-2026 00:05:00',
    nextRun: '15-Sep-2026 00:05:00',
    description: 'Calculates remaining balance for postpaid POP partners and enforces credit limits.',
    targetSubsystem: 'POP Ledger Engine',
    cronPattern: '05 00 * * *',
    recordsAffected: 4,
    lastRunDuration: '1.2s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-pop-2',
    branch: 'Main Branch',
    category: 'POP',
    processName: 'Prepaid POP Auto-Deduction & Quota Allocation',
    executeAt: '01:05',
    interval: 'Daily',
    executionDay: 'Today',
    status: 'Active',
    lastRun: '14-Sep-2026 01:05:00',
    nextRun: '15-Sep-2026 01:05:00',
    description: 'Daily deductions from prepaid POP wallets based on running active lines.',
    targetSubsystem: 'POP Wallet Service',
    cronPattern: '05 01 * * *',
    recordsAffected: 9,
    lastRunDuration: '1.8s',
    lastRunStatus: 'Success'
  },
  // POP Customer Tab Processes
  {
    id: 'proc-popc-1',
    branch: 'Main Branch',
    category: 'POP Customer',
    processName: 'Prepaid POP Clients Automatic Renewal & Disable',
    executeAt: '01:05',
    interval: 'Daily',
    executionDay: 'Today',
    status: 'Active',
    lastRun: '14-Sep-2026 01:05:00',
    nextRun: '15-Sep-2026 01:05:00',
    description: 'Auto-renews or locks client accounts attached to POP branches based on branch wallet status.',
    targetSubsystem: 'POP Customer Registry',
    cronPattern: '05 01 * * *',
    recordsAffected: 9,
    lastRunDuration: '1.9s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-popc-2',
    branch: 'Main Branch',
    category: 'POP Customer',
    processName: 'Sync All POP Customers With MikroTik CCR',
    executeAt: 'Default',
    interval: 'Hourly',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 10:00:00',
    nextRun: '14-Sep-2026 11:00:00',
    description: 'Synchronizes POP subscriber speed profiles and credentials with edge routers.',
    targetSubsystem: 'MikroTik API',
    cronPattern: '00 * * * *',
    recordsAffected: 115,
    lastRunDuration: '2.5s',
    lastRunStatus: 'Success'
  },
  // Bandwidth POP Tab Processes
  {
    id: 'proc-bw-1',
    branch: 'Main Branch',
    category: 'Bandwidth POP',
    processName: 'Generate Recurring Bandwidth Sale Invoice',
    executeAt: '03:00',
    interval: 'Daily',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '01-Sep-2026 03:00:00',
    nextRun: '01-Oct-2026 03:00:00',
    description: 'Generates wholesale recurring tax invoice for purchased bandwidth throughput.',
    targetSubsystem: 'Bandwidth Billing Module',
    cronPattern: '00 03 01 * *',
    recordsAffected: 8,
    lastRunDuration: '1.0s',
    lastRunStatus: 'Success'
  },
  {
    id: 'proc-bw-2',
    branch: 'Main Branch',
    category: 'Bandwidth POP',
    processName: 'Check Upstream Capacity & Peering Quota',
    executeAt: 'Default',
    interval: 'Hourly',
    executionDay: 'Tomorrow',
    status: 'Active',
    lastRun: '14-Sep-2026 10:00:00',
    nextRun: '14-Sep-2026 11:00:00',
    description: 'Polls upstream BDIX / IIG graphs and checks committed vs burstable bandwidth utilization.',
    targetSubsystem: 'SNMP Bandwidth Collector',
    cronPattern: '00 * * * *',
    recordsAffected: 4,
    lastRunDuration: '0.8s',
    lastRunStatus: 'Success'
  }
];

export const INITIAL_SMS_TEMPLATES: SmsTemplateItem[] = [
  {
    id: 1,
    name: 'Sales and Service Money Receipt Template',
    type: 'Default',
    template:
      'প্রিয় গ্রাহক, আপনার অ্যাকাউন্ট সম্পর্কিত তথ্য নিচে দেওয়া হলো: নাম: {CustomerName} ক্লায়েন্ট আইডি: {CustomerId} মোট বিল: {TotalAmount} ছাড়: {Discount} পরিশোধিত অর্থ: {PaidAmount} রশিদ নং: {ReceiptNo} ধন্যবাদ ও শুভেচ্ছা, {CompanyName}'
  },
  {
    id: 2,
    name: 'maintenance',
    type: 'Custom',
    template:
      'প্রিয় গ্রাহক, আজ রাত ১২ টা থেকে ৪ টা পর্যন্ত মেইন লাইনের রক্ষণাবেক্ষণের কারণে ইন্টারনেটে সাময়িক ধীরগতি বা সংযোগ বিঘ্ন হতে পারে। - BBN'
  },
  {
    id: 3,
    name: 'Greetings To Client Template',
    type: 'Default',
    template:
      'প্রিয় {CustomerName}, আপনার ইউনিক আইডি হচ্ছে {ClientCode}, সার্ভার আইপি: {ServerIp}, পাসওয়ার্ড: {Password}। ধন্যবাদ ও শুভেচ্ছা, BBN'
  },
  {
    id: 4,
    name: 'Bandwidth Sale Receipt',
    type: 'Default',
    template: 'প্রিয় গ্রাহক, ৳{ReceiptAmount} পরিশোধ হয়েছে। ইনভয়েস: {InvoiceId}। ধন্যবাদ - BBN'
  },
  {
    id: 5,
    name: 'Bandwidth Sale Invoice Notification',
    type: 'Default',
    template:
      'প্রিয় গ্রাহক, {Month} মাসের বিল বাকি। ইনভয়েস: {InvoiceId}, বকেয়া: ৳{Due}, বিল প্রদানের শেষ তারিখ: {PaymentDue} - BBN'
  }
];

export const ISP_PACKAGES = [
  {
    id: 'pkg-1',
    name: 'Starter Fiber',
    speed: '10 Mbps',
    speedRaw: '10mb_pkg_500tk',
    price: 500,
    features: ['Unlimited Data', 'Optical Fiber Link', '24/7 Phone Support', 'Public BDIX Cache 100Mbps', 'YouTube & Netflix HD Ultra'],
    popular: false
  },
  {
    id: 'pkg-2',
    name: 'Standard Pro',
    speed: '20 Mbps',
    speedRaw: '20mb_pkg_600tk',
    price: 600,
    features: ['Unlimited Data', 'Optical Fiber Link', 'Priority Routing', 'BDIX 100Mbps Full Duplex', '4K Streaming Ready'],
    popular: true
  },
  {
    id: 'pkg-3',
    name: 'Turbo Speed',
    speed: '50 Mbps',
    speedRaw: '50mb_pkg_800tk',
    price: 800,
    features: ['Ultra-Low Latency Gaming', 'Work-From-Home Optimized', 'Real Public IP Available', 'VIP Customer Queue', 'Gigabit BDIX Port'],
    popular: false
  },
  {
    id: 'pkg-4',
    name: 'Ultra Corporate',
    speed: '100 Mbps',
    speedRaw: '100mb_pkg_1000tk',
    price: 1000,
    features: ['Dedicated Optical Core', 'Static Public IP Included', 'SLA 99.9% Guaranteed', 'Direct Mikrotik Priority Queue', 'Enterprise Peering'],
    popular: false
  }
];

export const INITIAL_RECEIPTS = INITIAL_RECEIPTS_YOUNUS;
export const INITIAL_SERVERS = INITIAL_MIKROTIK_SERVERS;
export const INITIAL_POP_RESELLERS = INITIAL_POPS;
